services:
  reservationservice:
    image: reservationservice
    build:
      context: .
      dockerfile: ReservationService/Dockerfile
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ReservationServiceDev;Username=postgres;Password=admin

  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ReservationServiceDev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ReservationServiceDev"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/18/data
volumes:
  db-data:
  
